### ISSUE TITLE
三角形显示位置有问题

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/PP-Label-Frontend#10]
![83c9cd5842d79ada2715337000791a7](https://user-images.githubusercontent.com/71769312/157365064-1005e4de-5052-4522-9b85-368d35ce0cc1.png)

**Comment by cheneyveron** [comment]
https://github.com/PaddleCV-SIG/PP-Label-Frontend/commit/38e683c7814696ceaaf256bbd9615ba5836825f2
