### ISSUE TITLE
Move可以将多边形点移出图像边界，然后无法移动

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/PP-Label-Frontend#13]
![image](https://user-images.githubusercontent.com/71769312/158048151-674ee36f-946d-46fd-9a79-8f07580b71e5.png)

**Comment by cheneyveron** [comment]
https://github.com/PaddleCV-SIG/PP-Label-Frontend/commit/23e12a5e78561165030a45d7d01ec1cf16d5b170
