### ISSUE TITLE
模糊报错

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/PP-Label-Frontend#16]
貌似一些网络问题或者后端500在   serviceUtils.parseError(err, message); 之后只是显示 Something unexpected happened, please try again later. 报错很模糊

**Comment by Youssef-Harby** [comment]
Yes these errors because of Heroku, it's not responding for first 4 sec I think

**Comment by linhandev** [comment]
not really, sometimes errors like variable is not defined, pure js error is also vague. seems to be issue with the message function of antd. suggest console.log catched error message to avoid this

**Comment by linhandev** [comment]
heroku's cold start can take as long as 2 minutes /laugh

**Comment by cheneyveron** [comment]
Not considered a problem now. If backend provides 'detail' for non 2xx response, frontend always show detail.
