### ISSUE TITLE
Add adaptive size for detection page 

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/PP-Label-Frontend#22]

**Comment by cheneyveron** [comment]
Please be more specific. Adaptive size for which component on page?

**Comment by linhandev** [comment]
I was thinking about the whole page, or maybe its the stage area. but i think this is already fixed

**Comment by linhandev** [comment]
I was thinking about the whole page, or maybe its the stage area. but i think this is already fixed
