### ISSUE TITLE
[Enhancement]第一个task不显示标注

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/PP-Label-Frontend#24]
有时候分类从welcome进到第一个task的时候task有标注但是标签列表没显示，不稳定复现

**Comment by cheneyveron** [comment]
连续试了大概20次，未曾复现，观察中

**Comment by linhandev** [comment]
加上了那个timeout刷新这个问题应该有缓解

**Comment by linhandev** [comment]
我这边再win虚拟机中测试，什么东西都很慢，还是有一定概率触发这个。感觉那个timeout可以在弄一个长一点的

**Comment by linhandev** [comment]
加了一个2s的
