### ISSUE TITLE
welcome按钮有时候是纯白的

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/PP-Label-Frontend#32]
@cheneyveron

**Comment by linhandev** [comment]
![image](https://user-images.githubusercontent.com/29757093/176794059-f0e9fa6c-7ca8-465a-9bba-6e53fbb94a0f.png)

**Comment by cheneyveron** [comment]
如何复现？本地未曾成功复现

**Comment by linhandev** [comment]
不太清楚，我再关注一下，之前就是正常用，有些页面跳转之后就会有这个情况。先close了，再发现再reopen

**Comment by linhandev** [comment]
![image](https://user-images.githubusercontent.com/29757093/178114196-5b1ddd99-22b1-4ef6-8fdc-ef7d15e646b6.png)

又出现了一回，我这也是不稳定复现，没有明显的bug，感觉可能是antd或者react的问题

@cheneyveron
