### ISSUE TITLE
Interface size and scroll bar

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/PP-Label-Frontend#5]
like these images:
- 100%: it looks huge and incomplete
![image](https://user-images.githubusercontent.com/71769312/153350087-dc13fbb6-a615-4345-a790-5c0fcf3a8e40.png)
- 80%: it looks close to the design draft
![image](https://user-images.githubusercontent.com/71769312/153350127-b1ec9fba-d183-4b5b-a6a5-1c4a5afb7622.png)

**Comment by cheneyveron** [comment]
May I ask what's your screen resolution?

**Comment by geoyee** [comment]
> May I ask what's your screen resolution?

![image](https://user-images.githubusercontent.com/71769312/153355436-b26749ec-ce07-40a7-93e1-b74787f76362.png)

**Comment by cheneyveron** [comment]
It's still an issue for resolution under 1920*1080.
I'm still trying to adjust interface to fit the smallest as 1024*768
